const ModernTheme = {
  ltr: 'text-left',
  rtl: 'text-right',
  placeholder: 'editor-placeholder',
  paragraph: 'mb-4 leading-relaxed text-[#172b4d]',
  quote: 'border-l-4 border-[#0052cc] pl-4 italic text-[#434654] my-4 bg-[#f1f3ff] py-2 rounded-r-lg',
  heading: {
    h1: 'text-5xl font-black mb-6 text-[#041b3c] tracking-tighter',
    h2: 'text-4xl font-bold mb-4 text-[#041b3c] tracking-tight',
    h3: 'text-3xl font-bold mb-3 text-[#041b3c]',
    h4: 'text-2xl font-bold mb-2 text-[#041b3c]',
    h5: 'text-xl font-bold mb-1 text-[#041b3c]',
  },
  list: {
    ul: 'list-disc ml-8 mb-4 space-y-1',
    ol: 'list-decimal ml-8 mb-4 space-y-1',
    listitem: 'pl-1',
    nested: {
      listitem: 'list-none',
    },
  },
  image: 'editor-image',
  link: 'text-[#0052cc] underline cursor-pointer hover:text-[#0040a2]',
  text: {
    bold: 'font-black',
    italic: 'italic',
    overflowed: 'editor-text-overflowed',
    hashtag: 'editor-text-hashtag',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-[#f1f3ff] px-1.5 py-0.5 rounded font-mono text-sm text-[#d73a49]',
  },
  code: 'bg-[#1e1e1e] text-[#d4d4d4] p-6 rounded-xl font-mono text-sm block overflow-x-auto my-6 shadow-lg border border-white/5',
  codeHighlight: {
    atrule: 'text-[#c586c0]',
    attr: 'text-[#9cdcfe]',
    boolean: 'text-[#569cd6]',
    builtin: 'text-[#4ec9b0]',
    cdata: 'text-[#808080]',
    char: 'text-[#ce9178]',
    class: 'text-[#4ec9b0]',
    'class-name': 'text-[#4ec9b0]',
    comment: 'text-[#6a9955]',
    constant: 'text-[#569cd6]',
    deleted: 'text-[#ce9178]',
    doctype: 'text-[#808080]',
    entity: 'text-[#d4d4d4]',
    function: 'text-[#dcdcaa]',
    important: 'text-[#569cd6]',
    inserted: 'text-[#b5cea8]',
    keyword: 'text-[#569cd6]',
    namespace: 'text-[#d4d4d4]',
    number: 'text-[#b5cea8]',
    operator: 'text-[#d4d4d4]',
    prolog: 'text-[#808080]',
    property: 'text-[#9cdcfe]',
    punctuation: 'text-[#d4d4d4]',
    regex: 'text-[#d16969]',
    selector: 'text-[#d7ba7d]',
    string: 'text-[#ce9178]',
    symbol: 'text-[#569cd6]',
    tag: 'text-[#569cd6]',
    unit: 'text-[#b5cea8]',
    url: 'text-[#9cdcfe]',
    variable: 'text-[#9cdcfe]',
  },
  table: 'border-collapse table-auto w-full mb-8 border-2 border-[#e8edff] rounded-lg overflow-hidden',
  tableCell: 'border border-[#e8edff] p-4 text-sm',
  tableCellHeader: 'bg-[#f8f9fc] font-black text-[#041b3c] border-b-2 border-[#e8edff]',
};

export default ModernTheme;
